name: CI for UrlShortenerService

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      master_postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pswd
          POSTGRES_DB: url_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      master_redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the application
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Clean up Docker containers
        if: always()
        run: docker-compose down
